language: php

sudo: false
dist: trusty

git:
  depth: 3

notifications:
  email: false
  slack:
    secure: wOIYl99GbhtR+1zqM81ZqqY5Tr7sF0yRuDfRNLYQnFluonTZ7yE7CBB78LVFrBW7gKtE1TicPQLD+cb+cF1Url1PDccZWYbPlnFrV0GmDE6nFazLyzOmGIitYjNqdQC7AMU+OdfozWg5GF0BlNHOfWbKmCyohLWen12kfl0H44Y7oJwcHJ4FY0/Eaau+/L1WQlcfZm7O8mu0zM7lOrZOX8VPLUlJY7anCfDVq6/8kwwfLr15WCvWdIJl1TOmE+/QRFXyDKeqB3UQiaHli36R//PvC349NAZxKGmdaxfA+eu6a2ganlhXliQqkklU/kTtRGT7VWifGV6Ja0x/3Po3JsoVkW0A3f2xlGLXNOqyENTmC8DPqVXXrUF2oJzema8M2hQ1DeZyCU/cdSoD0OWtgneiZfCreO/oEqK7YzwxlJ/YW+GYxLwbr6Wpy60svzk7d3oGjIlqyNyoodjji8JkeuGAGThllS1kWN/4bA82d8nuWjt0/6Q+pORO+08T6FbiAH5Kaoc4Kz4DQoIgeB+YJuQkJTSakkXiJ0Whf6DTu5Wez+RkZnjz5cvEfYMM9dElSPlcziUF241J6QR5OweXBuybKo1+JTdzWr4NMd71tcu3KOSYs8GnjR9kDirED4UuC3FhoL5TVvD1lozn70IgGdE/kpwC+deb6gP/m9VEJ68=

branches:
  only:
    - master
    - "/^v[0-9\\.]+/"

cache:
  yarn: true
  directories:
    - "${HOME}/.composer/cache"
    - node_modules
    - "${TRAVIS_BUILD_DIR}/.plugin"
    - "${TRAVIS_BUILD_DIR}/.work/cache"

stages:
  - name: check
    if: branch = master and tag IS blank and type IN (pull_request, api, cron)
  - name: test
    if: branch = master and tag IS blank and type IN (pull_request, api)
  - name: test trunk
    if: branch = master and tag IS blank and type IN (pull_request, api, cron)
#  - name: prepare
#    if: branch = master and tag IS blank and type IN (pull_request, api)
  - name: deploy
    if: tag IS present

before_script:
  - git clone --depth=1 https://github.com/wp-content-framework/travis-ci.git travis-ci
  - bash travis-ci/bin/prepare.sh

jobs:
  fast_finish: true
  include:
    - stage: check
      language: php
      php: '7.2'
      script: bash travis-ci/bin/php/phpcs.sh
    - stage: check
      language: php
      php: '7.2'
      script: bash travis-ci/bin/php/phpmd.sh

    - stage: check
      language: node_js
      node_js: '11'
      dist: trusty
      script: bash travis-ci/bin/js/js-lint.sh


    - stage: test
      language: php
      php: '7.3'
      env:
        - WP_VERSION=latest
        - COVERAGE_REPORT=1
        - ACTIVATE_POPULAR_PLUGINS=1
      script: bash travis-ci/bin/php/wp-test.sh
    - stage: test
      language: php
      php: '7.3'
      env:
        - WP_VERSION=latest
        - WP_MULTISITE=1
      script: bash travis-ci/bin/php/wp-test.sh
    - stage: test
      language: php
      php: '7.2'
      env: WP_VERSION=latest
      script: bash travis-ci/bin/php/wp-test.sh
    - stage: test
      language: php
      php: '7.2'
      env:
        - WP_VERSION=5.2
        - WP_MULTISITE=1
        - COVERAGE_REPORT=1
      script: bash travis-ci/bin/php/wp-test.sh
    - stage: test
      language: php
      php: '7.1'
      env: WP_VERSION=latest
      script: bash travis-ci/bin/php/wp-test.sh
    - stage: test
      language: php
      php: '7.1'
      env: WP_VERSION=5.1
      script: bash travis-ci/bin/php/wp-test.sh
    - stage: test
      language: php
      php: '7.0'
      env:
        - WP_VERSION=latest
        - WP_MULTISITE=1
      script: bash travis-ci/bin/php/wp-test.sh
    - stage: test
      language: php
      php: '5.6'
      env:
        - WP_VERSION=latest
        - COVERAGE_REPORT=1
      script: bash travis-ci/bin/php/wp-test.sh
    - stage: test
      language: php
      php: '5.6'
      env:
        - WP_VERSION=5.2
        - WP_MULTISITE=1
        - COVERAGE_REPORT=1
      script: bash travis-ci/bin/php/wp-test.sh
    - stage: test
      language: php
      php: '5.6'
      env: WP_VERSION=3.9
      script: bash travis-ci/bin/php/wp-test.sh

    - stage: test
      language: node_js
      node_js: '10'
      dist: trusty
      script: bash travis-ci/bin/js/js-test.sh
    - stage: test
      language: node_js
      node_js: '11'
      dist: trusty
      env: COVERAGE_REPORT=1
      script: bash travis-ci/bin/js/js-test.sh


    - stage: test trunk
      language: php
      php: '7.3'
      env:
        - WP_VERSION=trunk
        - WP_MULTISITE=1
        - ACTIVATE_POPULAR_PLUGINS=1
      script: bash travis-ci/bin/php/wp-test.sh

    - stage: test trunk
      language: php
      php: '5.6'
      env: WP_VERSION=trunk
      script: bash travis-ci/bin/php/wp-test.sh


#    - stage: prepare
#      language: node_js
#      node_js: '11'
#      dist: trusty
#      script:
#        - source travis-ci/bin/deploy/env.sh
#        - bash travis-ci/bin/deploy/wp-check-diff.sh


    - stage: deploy
      language: node_js
      node_js: '11'
      dist: trusty
      script: skip
      before_deploy:
        - source travis-ci/bin/deploy/env.sh
        - bash travis-ci/bin/deploy/create.sh
      deploy:
        provider: releases
        skip_cleanup: true
        name: ${RELEASE_TITLE}
        tag_name: ${RELEASE_TAG}
        api_key:
          secure: u/TcTu8qT+XbB8XX2hGitscwb64/wGd3uvRr0sMR8irhBSN0d+Q9kvj+lIlfr2RYgXFOCgJoMWYBD2ss0O5lhbsT4g9pRiP2kw/Q0zbB0XqnG87rZRQDRzUz+i8jrMpL4w70+g34KSNYUO6mL5O4vFfpfGHawBGRAZHThpVVlHAdG4Nmtw3Q8lSnWjnoSogOK1g1iWssZg7DKizkm6Dg5nMM3INzdvKbEoWUywX3wpl8xPvMfI9XlPjn3sAfQyPWPAtGhPcyYLxwOdNKmFXc0dA2ZG0lFwMnCYaY2HMGdkSyZN/nQjDqKDUdxLfIDdYshRAcfjBG0/JoaU5i1IxaMfbqLR8vyTzTAakM1AGnLDijUkh2Pf9vrxL+rdJJu54XiGGjLZG5e8WIuEDGpt+UYfReFRbhOI6uWOFJXQgbD7Cp1BuPmMdPRr4NrNRLPw7vIhXYY5UCVKc83xt9tU35uQBj7gfYSSBHT9EdIFoUSH/PK8InXDOGy17OKB1vLLEiAJwgUFjMgPfuE0RUpGYDrDBBja7zHI/OxAvX+CLsWa81qzyjD3jY87cykhUqJxKO7K82/lr3dkRu6iIFNOJEdh01395RHEXGDOFP6OD/rEGq60H9no9dO8g3OgUURO/QhZQNoIRFNA0Co3A/hyJ2/HHaDtyF7rirnba3c/in2vQ=
        file: ${RELEASE_FILE}
        body: ${RELEASE_BODY}
        overwrite: true
        on:
          tags: true

#    - stage: deploy
#      language: node_js
#      node_js: '11'
#      dist: trusty
#      script: skip
#      before_deploy:
#        - source travis-ci/bin/deploy/env.sh
#      deploy:
#        provider: script
#        skip_cleanup: true
#        script: bash travis-ci/bin/deploy/wp-release.sh
#        on:
#          tags: true

    - stage: deploy
      language: node_js
      node_js: '11'
      dist: trusty
      env:
        - GH_PAGES_PLUGIN_SCRIPT="./index.min.js"
        - GH_PAGES_TITLE="Gutenberg Samples"
        - GH_PAGES_TEMPLATE=gutenberg
        - GH_PAGES_TRACKING_ID=UA-78163306-3
      script: skip
      before_deploy:
        - source travis-ci/bin/deploy/env.sh
        - bash travis-ci/bin/deploy/gh-pages.sh
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: ${GITHUB_TOKEN}
        keep_history: true
        local_dir: ${GH_PAGES_DIR}
        on:
          tags: true

  allow_failures:
    - env: WP_VERSION=5.1
    - env: WP_VERSION=5.0
    - env: WP_VERSION=4.9
    - env: WP_VERSION=3.9
